<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SAPbobsCOM">
      <HintPath>lib\SapB1\Interop.SAPbobsCOM.dll</HintPath>
      <Private>true</Private>
      <EmbedInteropTypes>false</EmbedInteropTypes>
    </Reference>
    <Reference Include="SAPbouiCOM">
      <HintPath>lib\SapB1\Interop.SAPbouiCOM.dll</HintPath>
      <Private>true</Private>
      <EmbedInteropTypes>false</EmbedInteropTypes>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CrystalDecisions.CrystalReports.Engine">
      <HintPath>lib\CrystalShared\CrystalDecisions.CrystalReports.Engine.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="CrystalDecisions.Shared">
      <HintPath>lib\CrystalShared\CrystalDecisions.Shared.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="lib\SapB1\Interop.SAPbobsCOM.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\SapB1\Interop.SAPbouiCOM.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\CrystalShared\CrystalDecisions.CrystalReports.Engine.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="lib\CrystalShared\CrystalDecisions.Shared.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="Forms\Form1.b1f">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\Invoice.rpt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.18.1"/>
    <PackageReference Include="MimeKit" Version="4.18.1"/>
  </ItemGroup>
</Project>