<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CrystalDecisions.CrystalReports.Engine">
      <HintPath>dll\CrystalDecisions.CrystalReports.Engine.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="CrystalDecisions.Shared">
      <HintPath>dll\CrystalDecisions.Shared.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>